# Generated by Django 3.2.16 on 2023-01-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
